name: Build and release

on:
  release:
    types: [released]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Master
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Verify .NET
      run: dotnet --info

    - name: Pack
      run: dotnet pack nng.csproj -c Release

    - name: Publish to NuGet Gallery
      run: dotnet nuget push bin/Release/*.nupkg --api-key ${{ secrets.NUGET }} --source https://api.nuget.org/v3/index.json
